#!/bin/sh
## Generate debug executable
RELEASE="../build/release"

if [ ! -d "$RELEASE" ] ; then
    mkdir -p "$RELEASE"
fi

## Generate release executable
cd "$RELEASE"
cmake -DCMAKE_BUILD_TYPE=Release ../..
make install -j4
